dist: trusty
language: cpp
compiler:
  - clang
  - gcc
before_install:
# - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
# - sudo apt-get update -qq
# - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev qttools5-dev-tools qt5-default libqt5gui5
  - sudo apt-get install libglu1-mesa-dev
install:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_HEADLESS ..
  - make -j 4
  - make install
  - cd ..
script:
  - cd build
  - ctest
  - cd ..
