language: cpp
compiler:
  - clang
  - gcc
install:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j 4
  - make install
  - cd ..
script:
  - cd build
  - ctest
  - cd ..
